language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t donutcoffee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true donutcoffee/react-test npm run test -- --coverage
  
after_success:
  - docker build -t donutcoffee/multi-client ./client
  - docker build -t donutcoffee/multi-nginx ./nginx
  - docker build -t donutcoffee/multi-server ./server
  - docker build -t donutcoffee/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push donutcoffee/multi-client
  - docker push donutcoffee/multi-nginx
  - docker push donutcoffee/multi-server
  - docker push donutcoffee/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-726792320032"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
